### ISSUE TITLE
cascading-hbase-hadoop2-mr1 depending on hadoop 2.2?

### ISSUE THREAD

**Issue by poneill00** [Cascading/cascading.hbase#7]
Hey,

when building with cascading-hbase-hadoop2-mr1 - 2.6 I'm getting hadoop 2.2 jarspulled in as dependency...is this expected?

Its causing runtime errors when I run against hadoop 2.5.2 (on the cascading vagrant vm)

**Comment by fs111** [comment]
I pushed out a new build, please try http://conjars.org/cascading-hbase/cascading-hbase-hadoop2-mr1/versions/2.6.1-wip-2

**Comment by fs111** [comment]
Closing. If the problem persists, please re-open.
