### ISSUE TITLE
cascading.hbase-hadoop2-tez: cascading.flow.FlowException- step failed

### ISSUE THREAD

**Issue by Nevil-DSOUZA** [Cascading/cascading.hbase#9]
Hey,
I am using the cascading-hadoop2-tez with Hadoop2TezFlowConnector .
hadoop version :2.6.0,Hbase:  0.98.12.1-hadoop2,Tez:0.6.1 
source  and sink as HBaseTap
while running the code we are getting ClassNotFoundException:<b> TableInputFormat</b>.

2015-06-12 09:20:56,479 INFO [AsyncDispatcher event handler] history.HistoryEventHandler: [HISTORY][DAG:dag_1434080989680_0001_1][Event:DAG_FINISHED]: dagId=dag_1434080989680_0001_1, startTime=1434081056374, finishTime=1434081056448, timeTaken=74, status=FAILED, diagnostics=Vertex failed, vertexName=AA839B5CDFD948B1AEDAE569401AB883, vertexId=vertex_1434080989680_0001_1_00, diagnostics=[Vertex vertex_1434080989680_0001_1_00 [AA839B5CDFD948B1AEDAE569401AB883] killed/failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input: 356812042F314BCF87D0FF9A81CD3D37 initializer failed, vertex=vertex_1434080989680_0001_1_00 [AA839B5CDFD948B1AEDAE569401AB883], org.apache.tez.dag.api.TezUncheckedException: java.lang.RuntimeException: java.lang.RuntimeException:<b> java.lang.ClassNotFoundException: Class cascading.hbase.helper.TableInputFormat not found</b>
    at org.apache.tez.mapreduce.hadoop.MRInputHelpers.generateOldSplits(MRInputHelpers.java:426)
    at org.apache.tez.mapreduce.hadoop.MRInputHelpers.generateInputSplitsToMem(MRInputHelpers.java:295)
    at org.apache.tez.mapreduce.common.MRInputAMSplitGenerator.initialize(MRInputAMSplitGenerator.java:122)
    at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:245)
    at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:239)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:239)
    at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:226)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class cascading.hbase.helper.TableInputFormat not found
    at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2106)
    at org.apache.hadoop.mapred.JobConf.getInputFormat(JobConf.java:689)
    at org.apache.tez.mapreduce.hadoop.MRInputHelpers.generateOldSplits(MRInputHelpers.java:424)
    ... 13 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class cascading.hbase.helper.TableInputFormat not found
    at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2074)
    at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2098)
    ... 15 more
Caused by: java.lang.ClassNotFoundException: Class cascading.hbase.helper.TableInputFormat not found
    at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:1980)
    at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2072)
    ... 16 more

<b>It worked for HadoopFlowConnector, but it is not working when we installed Tez and changed flow connector to Hadoop2TezFlowConnector and it is working for HFS Tap.

Please help us in solving this issue..</b>

**Comment by Nevil-DSOUZA** [comment]
Am currently trying  HFS to HBASE is working fine.However It is Not Working for HBASE to HFS/HBASE Tap .

**Comment by fs111** [comment]
That is odd. I checked the jar on conjars and it contains the TableInputFormat class, so technically it should work.

A couple of questions: Do you use a Tez cluster or local mode? How do you package your app?

**Comment by Nevil-DSOUZA** [comment]
I am working in Local mode

**Comment by fs111** [comment]
I talked to @cwensel and he said that there is a problem in Tez local mode and adding jars to the classpath. For more infor see here: https://github.com/Cascading/cascading/tree/3.0/cascading-hadoop2-tez#notes-and-known-issues

**Comment by Nevil-DSOUZA** [comment]
I am tried with two Cluster mode but i am  getting the same Exception <b>Class Not Found TableInputFormat class </b>.</br>It Working fine when HFS tap to HBASE But It not Working with HBASE to HFS Tap

**Comment by Nevil-DSOUZA** [comment]
HFS to HBASE Code (WORKING):

```
      FlowConnector flowConnector = new Hadoop2TezFlowConnector(properties);

    Tap source = new Hfs(new TextLine(), inputFile);
    Pipe parsePipe = new Each("insert", new Fields("line"), new RegexSplitter(new Fields("num", "lower", "upper"), " "));

    Fields keyFields = new Fields("num");
    String[] familyNames = { "left"};
    Fields[] valueFields = new Fields[] { new Fields("lower","upper") };

    @SuppressWarnings("rawtypes")
    Tap hBaseTap = new HBaseTap("multitable2", new HBaseScheme(keyFields, familyNames, valueFields),SinkMode.REPLACE);
```

HBASE to HFS Code (NOT WORKING):

```
     FlowConnector flowConnector = new Hadoop2TezFlowConnector(properties);
    Fields keyFields = new Fields("num");
    String[] familyNames = { "left"};
    Fields[] valueFields = new Fields[] { new Fields("lower","upper") };
    @SuppressWarnings("rawtypes")
    Tap hBaseTap = new HBaseTap("multitable2", new HBaseScheme(keyFields, familyNames, valueFields),SinkMode.UPDATE);

    Pipe parsePipe = new Each( "read", new Identity());

    Tap hBaseSinkTap = new Hfs(new TextLine(), inputFile,SinkMode.REPLACE);
```

**Comment by fs111** [comment]
Thanks for the clarification. I will take a deeper look and try to replicate the issue.

**Comment by fs111** [comment]
We think we know what is going on and why it works in one direction and not the other. If you package your app as a jar with a lib folder inside, the AM will not see cascading-hbase and will fail while calculating the splits. This does not happen from HDFS -> HBase, since the hdfs jars are part of hadoop and always on the classpath. Can you, as a workaround repackage your app as a fat-jar a.k.a uber-jar for the time being? That should fix the problem.

**Comment by Nevil-DSOUZA** [comment]
I don't have much knowledge on Maven. I am working on the below maven file: 

```
<?xml version="1.0" ?>
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven- 4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>

<parent>
    <groupId>org.jpmml</groupId>
    <artifactId>jpmml-cascading</artifactId>
    <version>1.2</version>
</parent>

<groupId>org.jpmml</groupId>
<artifactId>pmml-cascading-example</artifactId>

<name>JPMML Cascading example</name>
<description>JPMML Cascading example application</description>

<licenses>
    <license>
        <name>GNU Affero General Public License (AGPL) version 3.0</name>
        <url>http://www.gnu.org/licenses/agpl-3.0.html</url>
        <distribution>repo</distribution>
    </license>
</licenses>
<dependencies>

 <dependency>
   <groupId>sqlline</groupId>
 <artifactId>sqlline</artifactId>
  <version>1.1.6</version>
</dependency>
        <dependency>
        <groupId>cascading-hbase</groupId>
        <artifactId>cascading-hbase-hadoop2-tez</artifactId>
        <version>3.0.0</version>
    </dependency>
    <dependency>
        <groupId>com.twitter</groupId>
        <artifactId>parquet-tools</artifactId>
        <version>1.6.0rc4</version>
    </dependency>
    <dependency>
        <groupId>org.jpmml</groupId>
        <artifactId>pmml-cascading</artifactId>
        <version>1.2</version>
    </dependency>

    <dependency>
        <groupId>cascading</groupId>
        <artifactId>cascading-core</artifactId>
        <version>3.0.0</version>
    </dependency>
    <dependency>
        <groupId>cascading</groupId>
        <artifactId>cascading-hadoop2-tez</artifactId>
        <version>3.0.0</version>
    </dependency>

    <!-- Matches the cascading:cascading-hadoop dependency -->
    <dependency>
<groupId>org.apache.hadoop</groupId>
<artifactId>hadoop-client</artifactId>
<version>2.6.0</version>

      </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
     <artifactId>slf4j-log4j12</artifactId>
     <version>1.7.5</version>
     </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>1.3.3</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <artifactSet>
                            <includes>
                                <include>com.google.guava:guava</include>
                                <include>org.jpmml:pmml-evaluator</include>
                                <include>org.jpmml:pmml-manager</include>
                            </includes>
                        </artifactSet>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                        <minimizeJar>true</minimizeJar>
                        <relocations>
                            <relocation>
                                <pattern>com.google</pattern>
                                <shadedPattern>org.jpmml.com.google</shadedPattern>
                            </relocation>
                        </relocations>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>2.4</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                    <configuration>
                        <appendAssemblyId>true</appendAssemblyId>
                        <archive>
                            <manifest>
                                <mainClass>org.jpmml.cascading.Main</mainClass>
                            </manifest>
                        </archive>
                        <descriptors>
                            <descriptor>src/main/assembly/job.xml</descriptor>
                        </descriptors>
                        <finalName>example-${project.version}</finalName>
                        <filters>
                        <filter>
               <artifact>commons-logging:commons-logging</artifact>
               <includes>
                   <include>**</include>
               </includes>
            </filter>
                        </filters>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-deploy-plugin</artifactId>
            <version>2.8.1</version>
            <configuration>
                <skip>true</skip>
            </configuration>
        </plugin>
    </plugins>
</build>
```

</project>

<b>Please help us to solve this issue.</b>

**Comment by fs111** [comment]
We found out that even fat-jars will not work out of the box. We are
currently working on a fix.  Please see this discussion for reference:
https://groups.google.com/forum/#!topic/cascading-user/HmP7TetztG0

On Wed, Jun 17, 2015 at 3:35 AM, Nevil-DSOUZA notifications@github.com
wrote:

> I don't have much knowledge on Maven. I am working on the below maven
> file:
> 
> <?xml version="1.0" ?>
>  <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven- 4.0.0.xsd">
> <modelVersion>4.0.0</modelVersion>
> 
> <parent>
>     <groupId>org.jpmml</groupId>
>     <artifactId>jpmml-cascading</artifactId>
>     <version>1.2</version>
> </parent>
> 
> <groupId>org.jpmml</groupId>
> <artifactId>pmml-cascading-example</artifactId>
> 
> <name>JPMML Cascading example</name>
> <description>JPMML Cascading example application</description>
> 
> <licenses>
>     <license>
>         <name>GNU Affero General Public License (AGPL) version 3.0</name>
>         <url>http://www.gnu.org/licenses/agpl-3.0.html</url>
>         <distribution>repo</distribution>
>     </license>
> </licenses>
> <dependencies>
> 
>  <dependency>
>    <groupId>sqlline</groupId>
>  <artifactId>sqlline</artifactId>
>   <version>1.1.6</version>
> </dependency>
>         <dependency>
>         <groupId>cascading-hbase</groupId>
>         <artifactId>cascading-hbase-hadoop2-tez</artifactId>
>         <version>3.0.0</version>
>     </dependency>
>     <dependency>
>         <groupId>com.twitter</groupId>
>         <artifactId>parquet-tools</artifactId>
>         <version>1.6.0rc4</version>
>     </dependency>
>     <dependency>
>         <groupId>org.jpmml</groupId>
>         <artifactId>pmml-cascading</artifactId>
>         <version>1.2</version>
>     </dependency>
> 
> ```
> <dependency>
>     <groupId>cascading</groupId>
>     <artifactId>cascading-core</artifactId>
>     <version>3.0.0</version>
> </dependency>
> <dependency>
>     <groupId>cascading</groupId>
>     <artifactId>cascading-hadoop2-tez</artifactId>
>     <version>3.0.0</version>
> </dependency>
> 
> 
> <dependency>
> ```
> 
> <groupId>org.apache.hadoop</groupId>
> <artifactId>hadoop-client</artifactId>
> <version>2.6.0</version>
> 
> ```
>   </dependency>
> 
> <dependency>
>   <groupId>org.slf4j</groupId>
>  <artifactId>slf4j-log4j12</artifactId>
>  <version>1.7.5</version>
>  </dependency>
> ```
> 
> </dependencies>
> 
> <build>
>     <plugins>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-shade-plugin</artifactId>
>             <version>1.3.3</version>
>             <executions>
>                 <execution>
>                     <phase>package</phase>
>                     <goals>
>                         <goal>shade</goal>
>                     </goals>
>                     <configuration>
>                         <artifactSet>
>                             <includes>
>                                 <include>com.google.guava:guava</include>
>                                 <include>org.jpmml:pmml-evaluator</include>
>                                 <include>org.jpmml:pmml-manager</include>
>                             </includes>
>                         </artifactSet>
>                         <createDependencyReducedPom>false</createDependencyReducedPom>
>                         <minimizeJar>true</minimizeJar>
>                         <relocations>
>                             <relocation>
>                                 <pattern>com.google</pattern>
>                                 <shadedPattern>org.jpmml.com.google</shadedPattern>
>                             </relocation>
>                         </relocations>
>                     </configuration>
>                 </execution>
>             </executions>
>         </plugin>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-assembly-plugin</artifactId>
>             <version>2.4</version>
>             <executions>
>                 <execution>
>                     <phase>package</phase>
>                     <goals>
>                         <goal>single</goal>
>                     </goals>
>                     <configuration>
>                         <appendAssemblyId>true</appendAssemblyId>
>                         <archive>
>                             <manifest>
>                                 <mainClass>org.jpmml.cascading.Main</mainClass>
>                             </manifest>
>                         </archive>
>                         <descriptors>
>                             <descriptor>src/main/assembly/job.xml</descriptor>
>                         </descriptors>
>                         <finalName>example-${project.version}</finalName>
>                         <filters>
>                         <filter>
>                <artifact>commons-logging:commons-logging</artifact>
>                <includes>
>                    <include>**</include>
>                </includes>
>             </filter>
>                         </filters>
>                     </configuration>
>                 </execution>
>             </executions>
>         </plugin>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-deploy-plugin</artifactId>
>             <version>2.8.1</version>
>             <configuration>
>                 <skip>true</skip>
>             </configuration>
>         </plugin>
>     </plugins>
> </build>
> 
>  _Please help us to solve this issue._
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cascading/cascading.hbase/issues/9#issuecomment-112749248
> .

## 

André Kelpe
andre@concurrentinc.com
http://concurrentinc.com

**Comment by fs111** [comment]
So we have a fix, which is currently going through our CI server. Please give the next 3.0.1-wip build a try.

**Comment by Nevil-DSOUZA** [comment]
kudos...Thanks for helping us to Solve the issue .It working fine Now.

**Comment by fs111** [comment]
excellent. Thanks for bringing it to our attention.
